[package]
name = "semifold-resolver"
version = "0.4.0"
edition.workspace = true
description.workspace = true
license.workspace = true
documentation.workspace = true
homepage.workspace = true
repository.workspace = true
readme.workspace = true
authors.workspace = true

[lints]
workspace = true

[dependencies]
boa_engine = "0.21.1"
boa_gc = "0.21.1"
boa_runtime = { version = "0.21.1", default-features = false, features = ["fetch", "url"] }
camino = "1.2.4"
clap = { version = "4.5", features = ["derive"], optional = true }
git2 = { version = "0.20.2", features = ["vendored-openssl"] }
glob = "0.3.3"
http = "1.3"
log = "0.4.27"
pathdiff = "0.2.3"
regex = "1.11.1"
reqwest = { version = "0.12", default-features = false, features = ["rustls-tls-native-roots"] }
saphyr = "0.0.6"
semifold-core = { version = "0.1.0", path = "../semifold-core" }
semver = { version = "1.0.26", features = ["serde"] }
serde = { version = "1.0.219", features = ["derive"] }
serde_json = { version = "1.0.142", features = ["preserve_order"] }
sha2 = "0.10"
thiserror = "2.0.15"
tokio = { version = "1.48", features = ["rt-multi-thread", "net", "sync", "time"] }
toml_edit = { version = "0.23.3", features = ["serde"] }
ts-rs = { version = "12.0.1", features = ["semver-impl"], optional = true }

[dev-dependencies]
insta = "1.48.0"

[features]
ts-rs = ["dep:ts-rs"]
