[branches]
base = "main"
release = "release"

[tags]
chore = "Chores"
feat = "New Features"
fix = "Bug Fixes"
perf = "Performance Improvements"
refactor = "Refactors"

[packages."@semifold/docs"]
path = "docs"
resolver = "nodejs"

[packages."@semifold/plugin-sdk"]
path = "packages/plugin-sdk"
resolver = "nodejs"

[packages.semifold]
path = "crates/semifold"
resolver = "rust"
assets = ["artifacts/*"]

[packages.semifold-changelog]
path = "crates/changelog"
resolver = "rust"

[packages.semifold-core]
path = "crates/semifold-core"
resolver = "rust"

[packages.semifold-resolver]
path = "crates/resolver"
resolver = "rust"

[packages."@semifold/workspace"]
path = "."
resolver = "nodejs"

[packages.semifold-engine]
path = "crates/semifold-engine"
resolver = "rust"

[resolver.rust.pre-check]
type = "http"
url = "https://crates.io/api/v1/crates/{{ package.name }}/{{ package.version }}"
retry = [2, 5, 15, 30]

[[resolver.rust.publish]]
command = "cargo"
args = ["publish"]

[[resolver.rust.post-version]]
command = "cargo"
args = ["generate-lockfile"]
dry-run = true

[resolver.nodejs.pre-check]
type = "http"
url = "https://registry.npmjs.org/{{ package.name }}/{{ package.version }}"
retry = [2, 5, 15, 30]

[[resolver.nodejs.publish]]
command = "npm"
args = ["publish", "--provenance", "--access", "public", "--tag", "latest"]
