repos:
  - repo: https://github.com/crate-ci/typos
    rev: v1.48.0
    hooks:
      - id: typos
  - repo: local
    hooks:
      - id: cargo-format
        name: cargo format
        entry: cargo fmt -- --check
        language: system
        types: [text]
        files: "\\.(rs)$"
