[package]
name = "semifold-core"
version = "0.0.0"
edition.workspace = true
description.workspace = true
license.workspace = true
documentation.workspace = true
homepage.workspace = true
repository.workspace = true
authors.workspace = true
readme.workspace = true

[dependencies]
camino = "1.2.4"
semver = { version = "1.0.28", features = ["serde"] }
thiserror = "2.0.18"
