name: Semifold Status
on:
  pull_request_target:
    types: [opened, synchronize, reopened]
    branches: [main]

permissions:
  contents: write
  pull-requests: write
  issues: write

jobs:
  status:
    name: Status
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Cache rust artifacts
        uses: Swatinem/rust-cache@v2
      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy, rustfmt
      - name: Build
        run: cargo build --workspace
      - name: Semifold Status
        run: cargo run --bin semifold status --debug
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
